import type { Metadata } from "next";
import { Geist, Geist_Mono, Open_Sans } from "next/font/google";
import "./globals.css";
import { SessionProvider } from "next-auth/react";
import type { AppProps } from "next/app";
import ReactQueryProvider from "@/components/QueryProvider";
import SessionProviderWrapper from "@/components/SessionProviderWrapper";
import { Toaster } from "@/components/ui/sonner";
import SessionWatcher from "@/components/SessionWatcher";
// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const openSans = Open_Sans({
  subsets: ["latin"],
  weight: ["300", "400", "600", "700", "800"],
  variable: "--font-open-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const baseBg = `bg-gradient-to-t from-stone-100 via-sky-100 to-sky-300`;

  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} ${openSans.variable} antialiased h-screen w-screen font-mono ${baseBg}`}
      >
        <SessionProviderWrapper>
          <ReactQueryProvider>{children}</ReactQueryProvider>
          <Toaster
            theme="light"
            richColors
            position="top-right"
            className="base-sky-bg text-center text-2xl"
          />
          <SessionWatcher />
        </SessionProviderWrapper>
      </body>
    </html>
  );
}
